package data

import (
	"database/sql"
	"errors"
	"strings"
	"testing"

	. "github.com/infrago/base"
)

type migrationTestDialect struct{}

func (migrationTestDialect) Name() string              { return "sqlite" }
func (migrationTestDialect) Quote(value string) string { return `"` + value + `"` }
func (migrationTestDialect) Placeholder(int) string    { return "?" }
func (migrationTestDialect) SupportsILike() bool       { return false }
func (migrationTestDialect) SupportsReturning() bool   { return true }

type namedMigrationTestDialect struct{ name string }

func (d namedMigrationTestDialect) Name() string              { return d.name }
func (d namedMigrationTestDialect) Quote(value string) string { return `"` + value + `"` }
func (namedMigrationTestDialect) Placeholder(int) string      { return "?" }
func (namedMigrationTestDialect) SupportsILike() bool         { return false }
func (namedMigrationTestDialect) SupportsReturning() bool     { return true }

func TestBuildCreateTableDoesNotTurnValidatorNamesIntoSQLChecks(t *testing.T) {
	base := &sqlBase{conn: migrationTestConnection{}}
	query, err := base.buildCreateTableSQL("", "accounts", "id", Vars{
		"email":    Var{Type: "string", Check: "email"},
		"password": Var{Type: "string", Check: "password"},
		"score":    Var{Type: "integer", Check: "score >= 0"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(query, "CHECK (email)") || strings.Contains(query, "CHECK (password)") {
		t.Fatalf("validator name leaked into schema: %s", query)
	}
	if !strings.Contains(query, "CHECK (score >= 0)") {
		t.Fatalf("SQL check expression was removed: %s", query)
	}
}

func TestBuildCreateTableUsesNativeIntegerIdentity(t *testing.T) {
	tests := []struct {
		dialect string
		want    string
	}{
		{dialect: "sqlite", want: `"id" INTEGER PRIMARY KEY`},
		{dialect: "pgsql", want: `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`},
		{dialect: "mysql", want: `"id" BIGINT AUTO_INCREMENT PRIMARY KEY`},
	}
	for _, tt := range tests {
		t.Run(tt.dialect, func(t *testing.T) {
			base := &sqlBase{conn: namedMigrationTestConnection{dialect: tt.dialect}}
			query, err := base.buildCreateTableSQL("", "accounts", "id", Vars{
				"id":   Var{Type: "int"},
				"name": Var{Type: "string", Required: true},
			})
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(query, tt.want) {
				t.Fatalf("missing native identity %q in %s", tt.want, query)
			}
			if strings.Contains(query, `PRIMARY KEY ("id")`) {
				t.Fatalf("integer identity also received a table-level primary key: %s", query)
			}
		})
	}
}

func TestBuildCreateTableKeepsExplicitStringPrimaryKey(t *testing.T) {
	base := &sqlBase{conn: namedMigrationTestConnection{dialect: "pgsql"}}
	query, err := base.buildCreateTableSQL("", "settings", "code", Vars{
		"code":  Var{Type: "string", Required: true},
		"value": Var{Type: "string"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(query, `PRIMARY KEY ("code")`) {
		t.Fatalf("explicit string primary key was not preserved: %s", query)
	}
	if strings.Contains(query, "IDENTITY") {
		t.Fatalf("string primary key became an identity: %s", query)
	}
}

func TestMissingTableErrorsAcrossSQLDrivers(t *testing.T) {
	missing := []string{
		`pq: relation "public.accounts" does not exist`,
		`Error 1146 (42S02): Table 'main.accounts' doesn't exist`,
		`SQL logic error: no such table: accounts`,
		`unknown table 'accounts'`,
	}
	for _, message := range missing {
		if !isMissingTableError(errors.New(message)) {
			t.Fatalf("missing-table error was not recognized: %s", message)
		}
	}
	if isMissingTableError(errors.New("connection refused")) {
		t.Fatal("unrelated error was classified as a missing table")
	}
}

type migrationTestConnection struct{}

func (migrationTestConnection) Open() error      { return nil }
func (migrationTestConnection) Close() error     { return nil }
func (migrationTestConnection) Health() Health   { return Health{} }
func (migrationTestConnection) DB() *sql.DB      { return nil }
func (migrationTestConnection) Dialect() Dialect { return migrationTestDialect{} }

type namedMigrationTestConnection struct{ dialect string }

func (namedMigrationTestConnection) Open() error    { return nil }
func (namedMigrationTestConnection) Close() error   { return nil }
func (namedMigrationTestConnection) Health() Health { return Health{} }
func (namedMigrationTestConnection) DB() *sql.DB    { return nil }
func (c namedMigrationTestConnection) Dialect() Dialect {
	return namedMigrationTestDialect{name: c.dialect}
}
